services:
  marzban:
    build: .
    container_name: marzban
    restart: always
    env_file: .env
    volumes:
      - /var/lib/marzban:/var/lib/marzban
      - ./db:/code/db
      - ./config:/code/config
