services:
  marzban:
    build: .
    container_name: marzban
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
      - "10444:10444"
    volumes:
      - /var/lib/marzban:/var/lib/marzban
      - ./db:/code/db
      - ./config:/code/config
